project_id = "vnywuwuixejhaciovqli"

[functions.verify-captcha]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.verify-domain]
verify_jwt = false

[functions.export-backup]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.robots]
verify_jwt = false
